feat: annotation dictionary
MattiasBeming/LiU-AI-Project-Active-Learning-for-Music pull request #107
Opened 2021-12-17 14:24 UTC by tediiieee

Annotation class for saving annotations made by gui in a json file. 

Closes #82

2021-12-17 14:59 UTC, MattiasBeming requested changes

2021-12-17 14:59 UTC, MattiasBeming commented on src/phase_utils.py
> +class AnnotationStation:
Move AnnotationStation up in the file, and place it with the other classes

2021-12-17 14:59 UTC, MattiasBeming commented on src/phase_utils.py
> +            path (pathlib.Path): Path to dictionary in json format.
docstring: `(pathlib.Path)`
write `(Path)` instead

2021-12-17 14:59 UTC, MattiasBeming commented on src/phase_utils.py
> -
Personally i think the dividers are visually pleasing. 
But existing ones could be replaced by, for example:

```
###
# Classes
###
```

```
###
# Functions
###
```

Or

Split utility into 2 files. 
If this approach is taken, then make sure all code works.

2021-12-20 09:06 UTC, sporreking requested changes
Overall very good! all comments are about tiny details with docstrings. They should be quick to fix.

2021-12-20 09:06 UTC, sporreking commented on src/phase_utils.py
> +            FileNotFoundError: Raises error when path is not correct.
"Raises error" already specified. Skip this i.e. "Raises: FileNotFoundError: When the path is not valid."

2021-12-20 09:37 UTC, sporreking approved these changes
Amazing!

2021-12-20 09:45 UTC, MattiasBeming requested changes

2021-12-20 09:45 UTC, MattiasBeming commented on src/phase_utils.py
> +        self.path = path
`self.path` should use '_' to indicate an internal class variable:
`self._path`. 
Same goes for all class variables.

2021-12-20 10:34 UTC, MattiasBeming approved these changes

2021-12-20 10:45 UTC, merged