User phase
MattiasBeming/LiU-AI-Project-Active-Learning-for-Music pull request #108
Opened 2021-12-22 11:11 UTC by sporreking

Closes #34 
Closes #62

2021-12-28 18:48 UTC, caspiansusskind requested changes
Looks good! I left some comments about minor things that we should probably fix.

2022-01-02 16:29 UTC, sporreking commented on src/init_phase.py
> +               batch_size: int = 100, model_eval: bool = False):
Good catch! I had missed this in another place as well.

2022-01-02 16:29 UTC, sporreking commented on src/init_phase.py
>              f"res/data/features_librosa_{train}_{feat_sel}.npy"),
Indeed!

2022-01-02 16:43 UTC, caspiansusskind approved these changes
Looks great!

2022-01-03 09:53 UTC, merged