Tree regression
MattiasBeming/LiU-AI-Project-Active-Learning-for-Music pull request #68
Opened 2021-11-25 11:00 UTC by tediiieee

See commit msgs

Implemented tree regression

Also did:
refactors in ML
bugfixes in storage and transformer
Implemented new functions for accessing labels

Closes #23 
Closes #67

2021-11-26 07:34 UTC, sporreking requested changes
Use correct docstring in `decision_tree()`, even if other functions use incorrect format.

2021-11-26 07:34 UTC, sporreking commented on src/ml.py
> +def decision_tree(X, y):
Use correct docstring, even if other functions use incorrect format.

2021-11-26 07:37 UTC, Ludvig-Joborn approved these changes
Changes look great, good job!

2021-11-29 12:47 UTC, sporreking approved these changes
Looking good!

2021-11-29 12:47 UTC, merged